#!/bin/bash

# Copyright (C) 2014 Steve Murphy
# All Rights Reserved
# License (GNU Public License):
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
#    USA

rand1=`perl -e 'print int(rand(64000 - 20000)) +20000'`
rand2=`perl -e 'print int(rand(64000 - 20000)) +20000'`
while [ $rand1 = $rand2 ] ; do
 rand2=`perl -e 'print int(rand(64000 - 20000)) +20000'`
done
echo rand num is $rand1 and rand2 is $rand2

echo "#define SERVER_REPORT_PORT $rand1" > server_ports.h
echo "#define SERVER_PUB_PORT    $rand2" >> server_ports.h
