#!/bin/bash
#
# banshare-server	This shell script takes care of starting and stopping
#		the banshare (ban distribution mechanism)
#
# chkconfig: - 58 74
# description: banshare-server is distribution of fail2ban/psad/whatever bans.

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

if [ -f /etc/sysconfig/banshare-server ];then
        . /etc/sysconfig/banshare-server
fi
[ -f /usr/bin/banshare-server ]

RETVAL=0

start() {
        # Start daemons.
        echo -n $"Starting safe_banshare_server: "
	ulimit -s 512
        daemon /usr/bin/banshare-server $OPTIONS
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/banshare-server
	return $RETVAL
}

stop() {
        echo -n $"Shutting down safe_banshare_server: "
	killproc /usr/bin/banshare-server
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/banshare-server
	return $RETVAL
}

status() {
	isrunning=`ps aux|grep banshare-server|grep -v grep|grep -v status|grep -v vim|grep -v vi`

	if [ -n "$isrunning" ]
	then
		echo "banshare-server daemon is running"
	fi
	if [ -z "$isrunning" ]
	then
		echo "banshare-server daemon is *NOT* running"
	fi
	RETVAL=$?
	return $RETVAL;
}

# See how we were called.
case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  status)
	status
	RETVAL=$?
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  condrestart)
	if [ -f /var/lock/subsys/banshare-server ]; then
	    stop
	    start
	    RETVAL=$?
	fi
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        RETVAL=3
esac

exit $RETVAL

