#!/bin/bash

#TTY=

#
# Set options 
#

BANARGS=""
if [ -f /etc/sysconfig/banshare_server ]
then
  . /etc/sysconfig/banshare_server
fi

ulimit -c unlimited
ulimit -n 2048

#
# Don't die if stdout/stderr can't be written to
#
trap '' PIPE

run_banshare_server()
{
  while :
  do
    cd /tmp
    # There is no >>&
    /usr/bin/banshare_server # self- daemonizes; no need for redirection of output; there is none.
    EXITSTATUS=$?
    echo "banshare_server ended with exit status $EXITSTATUS" >> /var/log/syslog
    echo "Automatically restarting banshare_server"           >> /var/log/syslog
    sleep 1
    killall -q -9 banshare_server
    sleep 1
  done
}

run_banshare_server >/dev/null 2>&1 &

